INSERT INTO public.addons
(addons_name, addons_price, fk_store_id)
VALUES('ไข่ต้ม', 10, 1);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('หมูยอ', 10, 1);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('ขนมจีน', 10, 1);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('ปูดอง', 10, 1);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('กุ้ง', 10, 1);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('หมู', 10, 1);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('หมึก', 10, 1);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('ผักดอง', 10, 3);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('ซอสพริก', 10, 3);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('มายอง', 10, 3);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('ผัดสลัด', 10, 3);
INSERT INTO public.addons
(addons_name, addons_price,  fk_store_id)
VALUES('หัวไซเท้าดอง', 10, 3);
