INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(1, 1, 1);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(2, 1, 3);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(3, 1, 4);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(4, 1, 2);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(5, 2, 5);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(6, 2, 7);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(7, 2, 6);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(8, 3, 8);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(9, 3, 10);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(10, 3, 11);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(11, 3, 9);
INSERT INTO public.group_select_addons
(group_select_addons_id, fk_group_select, fk_addons)
VALUES(13, 3, 12);
