INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(1, 1, 1);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(2, 1, 2);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(3, 2, 1);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(4, 2, 2);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(5, 4, 1);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(6, 5, 1);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(7, 6, 3);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(8, 7, 3);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(9, 8, 3);
INSERT INTO public.food_group_select
(food_group_select_id, fk_food_id, fk_group_select_id)
VALUES(10, 9, 3);
